### ISSUE TITLE
sketch crashes when exporting with prototype links

### ISSUE THREAD

**Issue by saadsufyan** [sketch-hq/print-export-sketchplugin#15]

**Comment by udayms** [comment]
I am noticing the same error. I am on v57.1

**Comment by KocTbIJIb** [comment]
Same behaviour: crash on export page with hospots
Version: 61.1

**Comment by lazing** [comment]
print export plugin is not working, crashing every time

**Comment by bomberstudios** [comment]
Seems to be working as expected in v1.0.10 of the plugin, so closing
