### ISSUE TITLE
sketch crashes when exporting with symbols

### ISSUE THREAD

**Issue by dfanchi** [sketch-hq/print-export-sketchplugin#17]
I've Version 57.1 (83088) and it's enough to have one symbol used.

**Comment by Tafkadasoh** [comment]
I have the same issue! And I can confirm that the presence of any symbol is the issue. When detaching all contents of all symbols, the export does not crash.

**Comment by bomberstudios** [comment]
Seems to be working as expected in v1.0.10 of the plugin, so closing
