### ISSUE TITLE
Dialog does not show

### ISSUE THREAD

**Issue by brandonjp** [sketch-hq/print-export-sketchplugin#2]
When I select *Plugins > Print Export*, nothing happens.  The dialog does not show.  

So far I've tried 3 different sketch files and a blank new file, all with the same results.  

 * Does this plugin require a minimum version of Sketch?  *(I'm running v48.2 - 47327)*

 * Is there any sort of view Sketch log or debug console?

Thanks

**Comment by alanleyva** [comment]
Did you manage to solve this issue?
I'm experiencing the exact same problem, select Plugins > Print Export, nothing happens...

**Comment by brandonjp** [comment]
> Did you manage to solve this issue?

No change for me. I just gave up  😞

**Comment by bomberstudios** [comment]
should be fixed in v1.0.10
