### ISSUE TITLE
No print-export.sketchplugin in zipped folder

### ISSUE THREAD

**Issue by jcbbuller** [sketch-hq/print-export-sketchplugin#26]
There's no print-export.sketchplugin in zipped folder.

**Comment by bomberstudios** [comment]
As explained in the README, the zip files are available for download in the Releases tab.

The latest version can always be downloaded at this URL: https://github.com/sketch-hq/print-export-sketchplugin/releases/latest/download/print-export.sketchplugin.zip

**Comment by jcbbuller** [comment]
Who the heck reads the README for a sketch plugin!?
