### ISSUE TITLE
Does this plugin still work?

### ISSUE THREAD

**Issue by JensDebergh** [sketch-hq/print-export-sketchplugin#5]
I tried using this plugin to export my page.

- The plugin opens
- I'm able to choose the options I want
- I press export and pick a filename
- No file is created afterwards

Any suggestions?

**Comment by Nivekvb** [comment]
Still works on my machine...
1.Spotlight run 'Console'
2. Library/Logs > com.bohemiancoding.sketch3 > plugin log.log
3. find relevant error message?

**Comment by rjlegrange** [comment]
Experiencing a weird issue with installing this plugin. 
Opening from the plugin file, or dragging into the plugin manager results in *nothing*.
Tried others, like Confetti by Yummygum, and no worries. 
Have completely uninstalled SketchApp, setup anew and re-done registration. Still nothing. 
Any ideas?
